export const data = [
  {
    name: "Photo 1",
    url: "images/resim1.png",
    description: "redhead guy with pink and green haired kid",
    date: "2023-06-09",
    type: "image/png",
  },
  {
    name: "Photo 2",
    url: "/images/resim2.png",
    description: "3 guys versus volleyball guy",
    date: "2023-06-09",
    type: "image/png",
  },
  {
    name: "Photo 3",
    url: "/images/resim3.png",
    description: "gathering with a nice view",
    date: "2023-06-09",
    type: "image/png",
  },
  {
    name: "Photo 4",
    url: "/images/resim4.png",
    description: "camping with blue hat guy",
    date: "2023-06-09",
    type: "image/png",
  },
  {
    name: "Photo 5",
    url: "/images/resim5.png",
    description: "blue hat guy swings his weapon",
    date: "2023-06-09",
    type: "image/png",
  },
  {
    name: "Photo 6",
    url: "/images/resim6.png",
    description: "sensei and dragon in a mystic way",
    date: "2023-06-09",
    type: "image/png",
  },
  {
    name: "Photo 7",
    url: "/images/resim7.png",
    description: "sensei rubs his beard",
    date: "2023-06-09",
    type: "image/png",
  },
  {
    name: "Photo 8",
    url: "/images/resim8.png",
    description: "sitting together at sunset",
    date: "2023-06-09",
    type: "image/png",
  },
  {
    name: "Photo 9",
    url: "/images/resim9.png",
    description: "suprised looking boy",
    date: "2023-06-09",
    type: "image/png",
  },
];
